# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby-handlebars 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby-handlebars".freeze
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Vincent Pretre".freeze, "Hiptest R&D".freeze]
  s.date = "2019-06-26"
  s.email = "v.pretre@hiptest.net".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "lib/ruby-handlebars.rb",
    "lib/ruby-handlebars/context.rb",
    "lib/ruby-handlebars/escapers/dummy_escaper.rb",
    "lib/ruby-handlebars/escapers/html_escaper.rb",
    "lib/ruby-handlebars/helper.rb",
    "lib/ruby-handlebars/parser.rb",
    "lib/ruby-handlebars/template.rb",
    "lib/ruby-handlebars/tree.rb"
  ]
  s.homepage = "https://github.com/vincent-psarga/ruby-handlebars".freeze
  s.rubygems_version = "3.0.4".freeze
  s.summary = "Pure Ruby library for Handlebars templates".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<parslet>.freeze, ["~> 1.6", ">= 1.6.2"])
      s.add_development_dependency(%q<pry>.freeze, ["~> 0.10", ">= 0.10.1"])
      s.add_development_dependency(%q<pry-stack_explorer>.freeze, ["~> 0.4", ">= 0.4.9.1"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 3.1.0", "~> 3.1"])
      s.add_development_dependency(%q<rspec-mocks>.freeze, ["~> 3.1", ">= 3.1.3"])
      s.add_development_dependency(%q<codeclimate-test-reporter>.freeze, ["~> 0.4", ">= 0.4.6"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0", ">= 2.0.1"])
    else
      s.add_dependency(%q<parslet>.freeze, ["~> 1.6", ">= 1.6.2"])
      s.add_dependency(%q<pry>.freeze, ["~> 0.10", ">= 0.10.1"])
      s.add_dependency(%q<pry-stack_explorer>.freeze, ["~> 0.4", ">= 0.4.9.1"])
      s.add_dependency(%q<rspec>.freeze, [">= 3.1.0", "~> 3.1"])
      s.add_dependency(%q<rspec-mocks>.freeze, ["~> 3.1", ">= 3.1.3"])
      s.add_dependency(%q<codeclimate-test-reporter>.freeze, ["~> 0.4", ">= 0.4.6"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.0", ">= 2.0.1"])
    end
  else
    s.add_dependency(%q<parslet>.freeze, ["~> 1.6", ">= 1.6.2"])
    s.add_dependency(%q<pry>.freeze, ["~> 0.10", ">= 0.10.1"])
    s.add_dependency(%q<pry-stack_explorer>.freeze, ["~> 0.4", ">= 0.4.9.1"])
    s.add_dependency(%q<rspec>.freeze, [">= 3.1.0", "~> 3.1"])
    s.add_dependency(%q<rspec-mocks>.freeze, ["~> 3.1", ">= 3.1.3"])
    s.add_dependency(%q<codeclimate-test-reporter>.freeze, ["~> 0.4", ">= 0.4.6"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0", ">= 2.0.1"])
  end
end

